### ISSUE TITLE
Where does the qr-code image is generated ?

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/qr-bro#2]
Where can we define the qr-code path of the image

**Comment by emmanuelgeoffray** [comment]
check [standard-settings](https://github.com/soixantecircuits/standard-settings/) and the [default settings in project](https://github.com/soixantecircuits/qr-bro/blob/master/settings/settings.default.json)

**Comment by gabrielstuff** [comment]
ok, thanks, see https://github.com/soixantecircuits/qr-bro/issues/6
