### ISSUE TITLE
What event qr-bro is listening to ?

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/qr-bro#3]
What is the event qr-bro is listening to ?

**Comment by emmanuelgeoffray** [comment]
check [standard-settings](https://github.com/soixantecircuits/standard-settings/) and the [default settings in project](https://github.com/soixantecircuits/qr-bro/blob/master/settings/settings.default.json)

**Comment by gabrielstuff** [comment]
ok, thanks. See https://github.com/soixantecircuits/qr-bro/issues/6
