### ISSUE TITLE
Can we use something else than spacebro.space ?

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/qr-bro#4]
How to define our own spacebro server ?

**Comment by emmanuelgeoffray** [comment]
check [standard-settings](https://github.com/soixantecircuits/standard-settings/) and the [default settings in project](https://github.com/soixantecircuits/qr-bro/blob/master/settings/settings.default.json)

**Comment by gabrielstuff** [comment]
standard-settings is a node package. Does this project follow the same behaviour ?

`SERVICE_SPACEBRO_HOST=localhost python qr-bro.py`

**Comment by gabrielstuff** [comment]
ok, I guess we add to fix https://github.com/soixantecircuits/qr-bro/issues/6 for this behaviour
